ts: 0.01

robot: 
  robot_name: "robot_3ups_rpu"
  config: 1

actuators:
  v_sat: 9.5
  vp_conversion: [28.4628, 28.4628, 28.4628, 246.6779]

controller:
  kp: [27190.0, 27190.0, 27190.0, 361023.0]
  kv: [114.27, 114.27, 114.27, 491.32]

ref_path:
  q: "/home/paralelo4dofnew/ros2_eloquent_ws/parallel_robot/references/refeprism_indep_TRR8.txt"
  x: "/home/paralelo4dofnew/ros2_eloquent_ws/parallel_robot/references/refecart_TRR8_identificar.txt"

dir_kin:
  tol: 0.0000001
  iter: 30