robot_3ups_rpu:
  config:
    0:  [0.4 , 0.4 , 0.4 , 0.0 , 0.872664, 0.698131, 0.2 , 0.2 , 0.2 , 0.523598, 0.698131]
    1:  [0.4 , 0.4 , 0.4 , 0.15, 1.570796, 0.785398, 0.3 , 0.3 , 0.3 , 0.872664, 1.570796]
    2:  [0.4 , 0.4 , 0.4 , 0.15, 1.570796, 0.785398, 0.25, 0.25, 0.25, 0.087266 , 1.570796]
    3:  [0.3 , 0.3 , 0.3 , 0.0 , 0.087266 , 1.570796, 0.2 , 0.2 , 0.2 , 1.221730, 0.523598]
    4:  [0.4 , 0.4 , 0.4 , 0.15, 1.570796, 0.087266 , 0.15, 0.15, 0.15, 0.785398, 1.570796]
    5:  [0.3 , 0.3 , 0.3 , 0.15, 0.872664, 1.570796, 0.15, 0.15, 0.15, 1.570796, 0.785398]
    6:  [0.25, 0.25, 0.25, 0.15, 0.087266 , 1.570796, 0.15, 0.15, 0.15, 1.396263, 1.308996]
    7:  [0.35, 0.35, 0.35, 0.15, 1.570796, 0.436332, 0.2 , 0.2 , 0.2 , 1.047197, 1.570796]
    8:  [0.35, 0.35, 0.35, 0.15, 0.61086, 0.523598, 0.15, 0.15, 0.15, 0.087266 , 1.570796]

  physical_properties:
    p11:  [8.57287, -0.03389, 0.00102, 0.19460,  0.17087, -0.00050, 0.01739, 0.18719, 0.00007, 0.02096]
    p12:  [0.86261, 0.00000, 0.00000, -0.26250, 0.02278, 0.00000, 0.00000, 0.02278, 0.00000, 0.00004]
    p21:  [8.57287, 0.03389, -0.00102, 0.19460, 0.17087, -0.00050, -0.01739, 0.18719, -0.00007, 0.02096]
    p22:  [0.86261, 0.00000, 0.00000, -0.26250, 0.02278, 0.00000, 0.00000, 0.02278, 0.00000, 0.00004]
    p31:  [8.57287, 0.03389, -0.00102, 0.19460, 0.17087, -0.00050, -0.01739, 0.18719, -0.00007, 0.02096]
    p32:  [0.86261, 0.00000, 0.00000, -0.26250, 0.02278, 0.00000, 0.00000, 0.02278, 0.00000, 0.00004]
    p41:  [8.81275, 0.00098, 0.01742, 0.13758, 0.09592, 0.00044, 0.00021, 0.08853, -0.00208, 0.01168]
    p42:  [1.73524, 0.00000, 0.15148, 0.00000, 0.03115, 0.00000, 0.00000, 0.00056, 0.00000, 0.03091]
    pm:   [9.82033, 0.00393, -0.00181, 0.03710, 0.26398, 0.01131, 0.00083, 0.21707, -0.00038, 0.47887]

robot_5p:
  config:
    1:  [0.5, 0.45, 0.45, 0.15, 1.221730, 1.221730, 0.3, 0.3, 0.3, 0.174533, 0.174533]
    2:  [0.5, 0.5, 0.5, 0.15, 1.745329, 1.745329, 0.3, 0.3, 0.3, 0.174533, 0.174533]
    3:  [0.5, 0.5, 0.5, 0.15, 1.919862, 1.919862, 0.3, 0.3, 0.3, 0.174533, 0.174533]
    4:  [0.5, 0.4, 0.5, 0.15, 2.094395, 1.047197, 0.3, 0.3, 0.3, 0.174533, 0.174533]
    5:  [0.5, 0.35, 0.35, 0.15, 1.570796, 1.570796, 0.3, 0.3, 0.3, 0.174533, 0.174533]
    6:  [0.5, 0.5, 0.5, 0.15, 1.745329, 1.745329, 0.3, 0.3, 0.3, 0.174533, 0.174533]
    7:  [0.5, 0.5, 0.5, 0.15, 2.094395, 2.094395, 0.3, 0.3, 0.3, 0.174533, 0.174533]
    8:  [0.5, 0.45, 0.4, 0.15, 1.570796, 1.570796, 0.3, 0.3, 0.3, 0.174533, 0.174533]

  physical_properties:
    p11:  [4.1050, -0.0364, -0.0350, 0.1918, 0.0882, 0.0040, 0.0052, 0.0890, 0.0049, 0.0105]
    p12:  [1.2620, 0, 0, -0.1785, 0.0444, 0, 0, 0.0444, 0, 0.0001]
    p21:  [4.1050, -0.0364, -0.0350, 0.1918, 0.0882, 0.0040, 0.0052, 0.0890, 0.0049, 0.0105]
    p22:  [1.2620, 0, 0, -0.1785, 0.0444, 0, 0, 0.0444, 0, 0.0001]
    p31:  [4.1050, -0.0364, -0.0350, 0.1918, 0.0882, 0.0040, 0.0052, 0.0890, 0.0049, 0.0105]
    p32:  [1.2620, 0, 0, -0.1785, 0.0444, 0, 0, 0.0444, 0, 0.0001]
    p41:  [5.5890, 0.0006, 0.0110, 0.2575, 0.1889, 0.0002, -0.0003, 0.1856, -0.0082, 0.0067]
    p42:  [1.8450, 0, 0.1922, 0, 0.0070, 0, 0, 0.0000, 0, 0.0070]
    pm:   [8.5558, 0.0494, -0.0003, 0.0380, 0.0925, 0.0011, -0.0012, 0.3504, 0.0001, 0.4393]